version: '3.9'

services:
  flyway:
    image: flyway/flyway
    command: -url=jdbc:postgresql://db:5432/fresh-air -user=postgres -password=postgres -connectRetries=60 migrate
    volumes:
      - ./db/:/flyway/sql/
    depends_on:
      - db

  db:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=fresh-air

  fresh-air:
    restart: unless-stopped
    build: .
    ports:
      - 8080:8080
    depends_on:
      - db

volumes:
  db:
