CREATE TABLE TB_WINDOW_EVENTS
(
    ID            SERIAL      NOT NULL,
    REGISTERED_AT TIMESTAMPTZ NOT NULL,
    SENSOR        VARCHAR     NOT NULL,
    EVENT         VARCHAR     NOT NULL,
    ROOM          VARCHAR     NOT NULL,
    PRIMARY KEY (ID)
);


